version: '3.8'
services:
  orthanc:
    # image: jodogne/orthanc-plugins:latest
    image: jodogne/orthanc-python
    hostname: orthanc
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data - if not using MySQL
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - "8042:8042"
      - "4242:4242" # DICOM
    restart: unless-stopped